version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_build:
      - cp _readthedocs/html/pdf/document.pdf $READTHEDOCS_OUTPUT/html/rctab.pdf

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: ./scripts/mkdocs_plugins/link_stripper

mkdocs:
  configuration: mkdocs.yml
