name: Build Documentation

on:
  push:
    branches:
      - main
      - github-pages  # Adjust as needed

permissions:
  contents: read  # Only needs read permission since we're not pushing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4