name: Deploy Prebuilt MkDocs Sites

on:
  push:
    branches:
      - releases/**

  workflow_dispatch:

permissions:
  contents: write  # Allows pushing to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set Variables
      - name: Set Variables
        id: vars
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"

          # Manual mapping
          if [ "$BRANCH_NAME" == "releases/1.3.2/doc2.0" ]; then
            DEPLOY_DIR="1.3.2/doc2.0"
          elif [ "$BRANCH_NAME" == "releases/1.999/doc0.1" ]; then
            DEPLOY_DIR="1.999/doc0.1"
          else
            echo "Branch $BRANCH_NAME is not configured for deployment."
            exit 0  # Exit gracefully if the branch is not in the mapping
          fi

          echo "Deployment directory: $DEPLOY_DIR"

          # Set outputs
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "deploy_dir=$DEPLOY_DIR" >> $GITHUB_OUTPUT

      # Step 2: Checkout the source branch
      - name: Checkout Source Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.branch_name }}
          path: source_branch  # Use a separate directory

      # Step 3: Checkout gh-pages Branch
      - name: Checkout gh-pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0  # Ensure full history is fetched

      # Step 4: Deploy Site
      - name: Deploy Site
        run: |
          DEPLOY_DIR="${{ steps.vars.outputs.deploy_dir }}"
          echo "Deploying to gh-pages/$DEPLOY_DIR"

          mkdir -p gh-pages/"$DEPLOY_DIR"
          rm -rf gh-pages/"$DEPLOY_DIR"/*

          cp -a source_branch/site/* gh-pages/"$DEPLOY_DIR"/

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        working-directory: gh-pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add "$DEPLOY_DIR"

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Deploy $DEPLOY_DIR from ${{ steps.vars.outputs.branch_name }}"
            git push origin gh-pages
          fi